### ISSUE TITLE
Som forsker, vil jeg gerne kunne se historikdata på en specifik sensor i en graf, så jeg kan se hvad en sensor har samlet af data over tid.

### ISSUE THREAD

**Issue by troxdk** [MagpieTeam/presenter#11]
- [x] Forskeren skal kunne vælge en tidsperiode og se sin data i.
- [ ] Forskeren skal minimalt kunne vælge et interval på 1 måned (ca 2,6 mio datapunkter)
- [x] Forskeren vil gerne kunne se navn og sensor id.

**Comment by trarbr** [comment]
Vi har ændret strategien mht. visning af data i graf. Datasættet reduceres på server-siden vha. write-time aggregering, så man ikke skal hente mere end 100.000 data punkter for et givent interval.
